config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }
  resources :users, only: [:index, :edit, :update, :show] do
    collection do
      post :search
    end
  end

  root 'messages#index'

  resources :messages, :except => [:edit] do
    collection do
      get :sent
      post :search
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  validates :phone, presence: true
  validates :address, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, foreign_key: 'sender_id', class_name: 'User'
  belongs_to :receiver, foreign_key: 'receiver_id', class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :contact
  has_many :receiver_messages, :foreign_key=>'receiver_id', :class_name => 'Message'
  has_many :sender_messages, :foreign_key=>'sender_id', :class_name => 'Message'

  accepts_nested_attributes_for :contact

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @messages = current_user.receiver_messages
    respond_with(@messages)
  end

  def sent
    @messages = current_user.sender_messages
  end

  def show
    respond_with(@message)
  end

  def new
    @message = Message.new
    @receivers = User.where.not(id:current_user.id)
    respond_with(@message)
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        UserMailer.send_email(@message.sender.email, @message.receiver.email, @message.subject, @message.content).deliver
        format.html { redirect_to(@message, notice: 'User was successfully created.') }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
    @message.save
    #respond_with(@message)
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:sender_id, :receiver_id, :content)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource({})

    @validatable = devise_mapping.validatable?
    if @validatable
      @minimum_password_length = resource_class.password_length.min
    end

    self.resource.build_contact
    respond_with self.resource
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    # params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, contact_attributes:[:phone, :address]]
    # params.require(:user).permit(:first_name, :last_name, contacts:[:phone, :address])
    #devise_parameter_sanitizer.for(:sign_up) << :first_name
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    # params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    # devise_parameter_sanitizer.sanitize(:account_update)
    # devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name]
    # params.require(:user).permit(:first_name, :last_name, contacts:[:phone, :address])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessengerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main-container">
    <div class="container push-top">
      <div class="text-right actions push-bottom">
        <% if user_signed_in? %>
            Welcome <%= link_to current_user.full_name, edit_user_path(current_user.id) %>!
            <%= link_to 'Sign Out', :destroy_user_session, class: 'btn btn-danger', :method => :delete %>
        <% else %>
            <%= link_to 'Sign In', :new_user_session, class: 'btn btn-primary' %>
        <% end %>
      </div>
        <% if notice.present? %>
            <p class="alert notice alert-success"><%= notice %></p>
          <% end %>
        <% if alert.present? %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>

        <%= yield %>
    </div>
</div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :receiver_id %>
      <%= f.select :receiver_id, @receivers.collect{|u| [u.full_name, u.id]}, {}, {:class => 'form-control'} %>
    </div>

    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, :class => 'form-control', :rows => '5' %>
    </div>

  <div class="actions">
    <%= f.hidden_field :sender_id, :value => current_user.id %>
    <%= f.submit 'Send Message', :class => 'btn btn-primary' %>
    <%= link_to 'Back', messages_path, :class => 'btn btn-info' %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<%= form_tag '/messages/search', method: :post do %>
    <%= text_field_tag :search, '' %>
    <%= text_field_tag :d, '' %>
    <%= submit_tag 'Submit' %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Sender</th>
      <!--<th>Receiver</th>-->
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender.full_name %></td>
        <!--<td><%= message.receiver.full_name %></td>-->
        <td><%= message.content %></td>
        <td><i class="glyphicon glyphicon-book"></i> <%= link_to 'Show', message %></td>
        <td><i class="glyphicon glyphicon-remove"></i> <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'All Users', users_path, {class: 'btn btn-primary'} %>
<%= link_to 'New Message', new_message_path, class:'btn btn-primary' %>
<%= link_to 'View Sent Messages', sent_messages_path, class:'btn btn-primary' %>

app/views/messages/new.html.erb
<div class="row">
  <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-2">
    <h1 class="text-center">Send message</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/messages/sent.html.erb
<h1>All messages</h1>

<table class="table">
  <thead>
  <tr>
    <th>Sender</th>
    <!--<th>Receiver</th>-->
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender.full_name %></td>
        <!--<td><%= message.receiver.full_name %></td>-->
        <td><%= message.content %></td>
        <td><i class="glyphicon glyphicon-book"></i> <%= link_to 'Show', message %></td>
        <td><i class="glyphicon glyphicon-remove"></i> <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path, class:'btn btn-primary' %>
<%= link_to 'View Received Messages', messages_path, class:'btn btn-primary' %>

app/views/messages/show.html.erb
<blockquote>
    <p><%= @message.content %></p>
    <footer><%= @message.sender.full_name %></footer>
</blockquote>

<%= link_to 'Back', messages_path, :class=>'btn btn-info' %>

app/views/users/search.html.erb
<h1>Listing users</h1>

<%= form_tag '/users/search', method: :post do %>
    <%= text_field_tag :search, '' %>
    <%= submit_tag 'Submit' %>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th>User Name</th>
    <th>Email address</th>
    <th>Phone Number</th>
    <th>Address</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, edit_user_path(user.id) %></td>
        <td><%= user.email %></td>
        <td><%= user.contact.phone if user.contact.present? %></td>
        <td><%= user.contact.address if user.contact.present? %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'pull-left' %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' && controller_name != 'passwords' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:'pull-left' %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name == 'passwords' %>
    <%= link_to "Sign up", new_registration_path(resource_name), class:'pull-right' %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:'pull-right' %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <h1>Welcome <%= current_user.first_name %> <%= current_user.last_name %>!</h1>
<% else%>
    <h1>Welcom Guest!</h1>
<% end%>
<p>Enjoy on out app!</p>

<%= link_to 'All Users', users_path, {class: 'btn btn-primary'} %>
<%= link_to 'New Message', new_message_path, {class: 'btn btn-primary'} %>
<%= link_to 'Sign Out', :destroy_user_session, class: 'btn btn-danger', :method => :delete %>